export { default as Dashboard } from './Dashboard'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Map } from './Map/Map'
export { default as Product } from './Product/Product'
