export { default as Home } from './Home'
export { default as Map } from './Map'
export { default as Dashboard } from './Dashboard'
export { default as Login } from './Login'
export { default as Product } from './Products/Product'
